-- SCRIPT DE BANCO DE DADOS REFERENTE AO PROJETO INDIVIDUAL DE PESQUISA E INOVAÇÃO

-- CRIANDO E USANDO O BANCO DE DADOS MaiasCooking.
CREATE DATABASE MaiasCooking;
USE MaiasCooking;

CREATE TABLE pessoa(
idPessoa INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE receita(
idReceita INT PRIMARY KEY AUTO_INCREMENT
);